# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop'
gem 'sinatra' # https://github.com/sinatra/sinatra
gem 'sinatra-contrib'
gem 'sinatra-reloader'
gem 'puma'

gem "google-cloud-pubsub-v1" # https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-pubsub-v1
