# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop'
# https://github.com/sinatra/sinatra
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
# gem 'webrick'

# ===
# https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-pubsub-v1
gem "google-cloud-pubsub-v1"
