version: "3"
services:
  grafana:
    image: grafana/grafana:8.2.6 # https://hub.docker.com/r/grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment: # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#install-plugins-in-the-docker-container
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - grafana-simple-json-datasource
