version: '3'
services:
  db:
    image: postgres
    platform: linux/amd64
    environment: 
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/resque:/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
