# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra"

# Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
# 下のgemを追加で記述
gem "webrick", "~> 1.7"


