version: "3"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins