version: '3'
services:
  db:
    image: postgres
    # platform: linux/amd64
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  # pgweb:
  #   image: sosedoff/pgweb
  #   platform: linux/amd64
  #   links:
  #     - postgres:postgres
  #   ports:
  #     - '8081:8081'
  #   # environment:
  #   #   # DATABASE_URL: postgres://root:password@database:5432/learning_sql?sslmode=disable
  #   #   DATABASE_URL: postgres://user:password@host:port/database?sslmode=disable
  #   expose:
  #     - 8081
  #   command: /usr/bin/pgweb --bind=pgweb --listen=8081
  #   restart: always
  #   depends_on:
  #     - postgres

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db

# volumes:
#   postgres-data:
#     driver: local
